### PR TITLE
Update producer cache after creation

### PR DESCRIPTION
**Pull request by basvandenbrink**

### CODE REVIEW

**Comment by basvandenbrink** [comment]
Fixes issue #43.

**Comment by BenFradet** [comment]
Thanks a lot merging (can't believe this passed through)!

**Comment by basvandenbrink** [comment]
You're welcome! I'm glad I could help a little bit.

**Comment by BenFradet** [comment]
@basvandenbrink ahah just saw that it was working before thanks to https://github.com/BenFradet/spark-kafka-writer/blob/master/spark-kafka-0-10-writer/src/main/scala/com/github/benfradet/spark/kafka010/writer/KafkaProducerCache.scala#L42

However I do agree that `getOrElseUpdate` simplifies things a bit.

**Comment by basvandenbrink** [comment]
Ah, you're right. It wasn't a problem in the first place.

**Pull request merged**
